---
title: "beta-diversity"
output:
  html_notebook:
    code_fold: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(ggpubr)
library(dplyr)
library(ape)
library(vegan)
library(RColorBrewer)
library(patchwork)
source("../TEST.functions.R") #这里加载写好的功能，后面用到的ttFun，tkFun
source("../common.R")

do.write<-F

#phenotype
load("../../Result/01.Profile/phe1.RData")
load("../../Result/01.Profile/relDaysgroups.RData")
phe <- phe.210701%>%filter(Fecal.sample.name%in%fecn.w50) # 剔除样本
phe <- phe%>%filter(sample_order=="1"|sample_order=="-") 
#phe <- phe%>%filter(Antibiotic.use == "No")
```


### 多次用药一致 + 多次用药不一致的病人(共52个)
```{r}
p12 <- phe.210701%>%filter(sample_order=="1"|sample_order=="2")
c12 <- p12%>%filter(Patient.ID%in%diff2sam) # 不同疗法
s12 <- p12[-which(p12$Patient.ID%in%c12$Patient.ID),] # 相同疗法

c12.bray.dist <- genus.euclidean.dist[c12$Fecal.sample.name, c12$Fecal.sample.name]
s12.bray.dist <- genus.euclidean.dist[s12$Fecal.sample.name, s12$Fecal.sample.name]
#c12.bray.dist <- phy.euclidean.dist[c12$Fecal.sample.name, c12$Fecal.sample.name]
#s12.bray.dist <- phy.euclidean.dist[s12$Fecal.sample.name, s12$Fecal.sample.name]


rm(c122)
for (i in seq(1,nrow(c12.bray.dist),2)){
  tmpd <- data.frame(ID1=as.character(c12$Fecal.sample.name[i]),ID2=as.character(c12$Fecal.sample.name[i+1]), dist=as.numeric(c12.bray.dist[i,i+1]))
  if(exists("c122")){
    c122 <- rbind(c122, tmpd)
  }else{
    c122 <- tmpd
  }
}
c122$group <- "same subject(diff treatment)"


rm(s122)
for (i in seq(1,nrow(s12.bray.dist),2)){
  tmpd <- data.frame(ID1=as.character(s12$Fecal.sample.name[i]), ID2=as.character(s12$Fecal.sample.name[i+1]), dist=as.numeric(s12.bray.dist[i,i+1]))
  if(exists("s122")){
    s122 <- rbind(s122, tmpd)
  }else{
    s122 <- tmpd
  }
}
s122$group <- "same subject(same treatment)"


bray.dat <- rbind(c122,s122)
bray.dat$dist <- as.numeric(bray.dat$dist)

p1 <- ggplot(bray.dat, aes(x=group, y=dist,fill=group))+geom_boxplot()+theme_classic()+ stat_compare_means(label = "p.format",method = "wilcox.test",size=3)+
  labs(title="", x="", y="distance(bray curitis)")+theme_classic()
p1

if(do.write){
  ggsave(p1,width = 7, height = 4, filename = "../../Result/04.Globalview/2.Beta/beta.bray.diff.same.boxplot.genus.pdf")
}
```


# genus
```{r}

genus.prf <- read.table("../../Result/01.Profile/genus.rela.abun.xls")
genus.bray.dist <- read.table("../../Result/01.Profile/genus_beta.matrix.xls")
genus.euclidean.dist <-as.matrix(vegdist(t(genus.prf),"euclidean",binary=TRUE))#euclidean距离,即欧式距离
```


```{r}
# bray curitis

g5.genus.bray.df <- reshapeDist(genus.bray.dist,phe,"Fecal.sample.name","Group","BE2")
colnames(g5.genus.bray.df)[1:2] <- c("Group","BE2")

g10.genus.bray.df <- reshapeDist(genus.bray.dist,phe,"Fecal.sample.name","Drug_type","BE2")
colnames(g10.genus.bray.df)[1:2] <- c("Drug_type","BE2")

g3.genus.bray.df <- reshapeDist(genus.bray.dist,phe,"Fecal.sample.name","Treatment_type","BE2")
colnames(g3.genus.bray.df)[1:2] <- c("Treatment_type","BE2")

```


### 大组间比较
```{r}
load("../../Result/04.Globalview/g2g.compare.RData")

ggplot(g3.genus.bray.df, aes(x=Treatment_type, y=dist,fill=Treatment_type))+ 
  geom_boxplot(outlier.shape=NA)+theme_classic() + theme() +
  labs(title="Genus | Beta diversity(bray)", x="", y="distance")+ 
  stat_compare_means(comparisons=compare_g3,label = "p.format",method = "wilcox.test",size=3) +
ggplot(g3.genus.bray.df, aes(x=Treatment_type, y=dist, fill=BE2))+ 
  geom_boxplot(outlier.shape=NA)+theme_classic() + 
  theme(legend.direction = "horizontal",legend.position=c(0.7,0.2)) +
  stat_compare_means(label="p.format")


ggplot(g10.genus.bray.df, aes(x=Drug_type, y=dist, fill=Drug_type))+ 
  geom_boxplot(outlier.shape=NA)+theme_classic() + 
  theme(axis.text.x = element_text(angle = 15)) +
  labs(title="Genus | Beta diversity(bray)", x="", y="distance")+ 
  stat_compare_means(comparisons=compare_g10,label = "p.format",method = "wilcox.test",size=3)+
  #stat_compare_means(label="p.format")
ggplot(g10.genus.bray.df, aes(x=Drug_type, y=dist, fill=BE2))+ 
  geom_boxplot(outlier.shape=NA)+theme_classic() + 
  theme(legend.direction = "horizontal",legend.position=c(0.7,0.2),axis.text.x = element_text(angle = 15)) +
  labs(title="Beta diversity(bray)", x="", y="distance")+
  stat_compare_means(label="p.format")

```

### 亚组间比较
```{r}
ggplot(g5.genus.bray.df, aes(x=Group, y=dist, fill = Group))+ 
  geom_boxplot()+theme_classic() + 
  theme() +
  labs(title="Genus | Beta diversity(bray)", x="", y="distance")+ 
  stat_compare_means(comparisons=compare_g5,label = "p.format",method = "wilcox.test",size=3)+
ggplot(g5.genus.bray.df, aes(x=Group, y=dist, fill=BE2))+ 
  geom_boxplot(outlier.shape=NA)+theme_classic() + 
  theme(legend.direction = "horizontal",legend.position=c(0.7,0.2)) +
  labs(title="Genus | Beta diversity(bray)", x="", y="distance")+ 
  stat_compare_means(label="p.format")

## 拟和曲线 --Beta多样性画不了拟合曲线，因为样本太少
# phe$Ws <- ifelse(phe$Sampling.post.treatment.w.<10,"0w-10w",ifelse(phe$Sampling.post.treatment.w.<20,"10w-20w", ">20w"))
# g5.genus.bray.df <- reshapeDist(genus.bray.dist,phe,"Fecal.sample.name","BE2","Ws")
# colnames(g5.genus.bray.df)[1:2] <- c("BE2","Ws")
# ggplot(g5.genus.bray.df, aes(x=Ws, y=dist)) + geom_point(aes(color=BE2))+stat_smooth(method=lm,aes(color=BE2), alpha = 0.2)+theme_bw()+xlab("Weeks relative to initiation of treatment")


```


```{r}
#PCoA

pcoa_bray <- pcoa(genus.bray.dist) 
pcoa_data <- data.frame(pcoa_bray$vectors[,1:2])
colnames(pcoa_data) <- c("PC1", "PC2")
eig <- pcoa_bray$value[,1]
pc1 <- eig[1]/sum(eig)*100
pc2 <- eig[2]/sum(eig)*100
pc1 <- paste0("PC1(",round(pc1,2),"%)")
pc2 <- paste0("PC2(",round(pc2,2),"%)")

### merge data frame
rownames(phe) <- phe$Fecal.sample.name
pcoa_data<-merge(pcoa_data, phe, by = "row.names")


ggplot(pcoa_data,aes(x=PC1,y=PC2,color=Native.place)) + geom_point() + stat_ellipse(aes(color=Native.place)) + xlab(pc1)+ylab(pc2) 
ggplot(pcoa_data,aes(x=PC1,y=PC2,color=Drug_type)) + geom_point() + stat_ellipse(aes(color=Drug_type)) + xlab(pc1)+ylab(pc2) 
ggplot(pcoa_data,aes(x=PC1,y=PC2,color=Treatment_type)) + geom_point() + stat_ellipse(aes(color=Treatment_type)) + xlab(pc1)+ylab(pc2) 
ggplot(pcoa_data,aes(x=PC1,y=PC2,color=Group)) + geom_point() + stat_ellipse(aes(color=Group)) + xlab(pc1)+ylab(pc2) 

ggplot(pcoa_data,aes(x=PC1,y=PC2,color=BE2)) + geom_point() + facet_wrap(~Drug_type,ncol=4) +
  coord_fixed() + theme(legend.position = "top") + stat_ellipse(aes(color=BE2)) +
  xlab(pc1)+ylab(pc2) 

ggplot(pcoa_data,aes(x=PC1,y=PC2,color=BE2)) + geom_point() + facet_wrap(~Group,ncol=2) +
  coord_fixed() + theme(legend.position = "top") + stat_ellipse(aes(color=BE2)) +
  xlab(pc1)+ylab(pc2) 

ggplot(pcoa_data,aes(x=PC1,y=PC2,color=BE2)) + geom_point() + facet_wrap(~Treatment_type,ncol=2) +
  coord_fixed() + theme(legend.position = "top") + stat_ellipse(aes(color=BE2)) +
  xlab(pc1)+ylab(pc2)

```




#gene

```{r}

gene.bray.dist <- read.table("../../Result/01.Profile/genes_beta.matrix.xls")

```

```{r}
# bray curitis

g10.gene.bray.df <- reshapeDist(gene.bray.dist,phe,"Fecal.sample.name","Drug_type","BE2")
colnames(g10.gene.bray.df)[1:2] <- c("Drug_type","BE2")

g5.gene.bray.df <- reshapeDist(gene.bray.dist,phe,"Fecal.sample.name","Group","BE2")
colnames(g5.gene.bray.df)[1:2] <- c("Group","BE2")

g3.gene.bray.df <- reshapeDist(gene.bray.dist,phe,"Fecal.sample.name","Treatment_type","BE2")
colnames(g3.gene.bray.df)[1:2] <- c("Treatment_type","BE2")


```


### 大组间比较
```{r}

ggplot(g3.gene.bray.df, aes(x=Treatment_type, y=dist,fill=Treatment_type))+ 
  geom_boxplot(outlier.shape=NA)+theme_classic() + 
  theme() +
  labs(title="Gene | Beta diversity(bray)", x="", y="distance")+ 
  stat_compare_means(comparisons=compare_g3,label = "p.format",method = "wilcox.test",size=3)+
ggplot(g3.gene.bray.df, aes(x=Treatment_type, y=dist, fill=BE2))+ 
  geom_boxplot(outlier.shape=NA)+theme_classic() + 
  theme(legend.direction = "horizontal",legend.position=c(0.7,0.2)) +
  labs(title="Gene | Beta diversity(bray)", x="", y="distance")+ 
  stat_compare_means(label="p.format")

ggplot(g10.gene.bray.df, aes(x=Drug_type, y=dist, fill=Drug_type))+ 
  geom_boxplot(outlier.shape=NA)+theme_classic() + 
  theme(axis.text.x = element_text(angle = 15)) +
  labs(title="Gene | Beta diversity(bray)", x="", y="distance")+ 
  stat_compare_means(comparisons=compare_g10,label = "p.format",method = "wilcox.test",size=3)+
ggplot(g10.gene.bray.df, aes(x=Drug_type, y=dist, fill=BE2))+ 
  geom_boxplot(outlier.shape=NA)+theme_classic() + 
  theme(legend.direction = "horizontal",legend.position=c(0.7,0.2),axis.text.x = element_text(angle = 15)) +
  labs(title="Gene | Beta diversity(bray)", x="", y="distance")+ 
  stat_compare_means(label="p.format")

```



```{r}
ggplot(g5.gene.bray.df, aes(x=Group, y=dist, fill = Group))+ 
  geom_boxplot()+theme_classic() + 
  theme() +
  labs(title="Gene | Beta diversity(bray)", x="", y="distance")+ 
  stat_compare_means(comparisons=compare_g5,label = "p.signif",method = "wilcox.test",size=3)+
ggplot(g5.gene.bray.df, aes(x=Group, y=dist, fill=BE2))+ 
  geom_boxplot(outlier.shape=NA)+theme_classic() + 
  theme(legend.direction = "horizontal",legend.position=c(0.7,0.2)) +
  labs(title="Gene | Beta diversity(bray)", x="", y="distance")+ 
  stat_compare_means(label="p.format")

ggplot(g5.gene.bray.df%>%filter(Group=="ICT"), aes(x=Group, y=dist, fill=BE2))+ 
  geom_boxplot(outlier.shape=NA)+theme_classic() + 
  theme(legend.direction = "horizontal",legend.position=c(0.7,0.2)) +
  labs(title="Gene | Beta diversity(bray)", x="", y="distance")+ 
  stat_compare_means(label="p.format")

ggplot(g10.gene.bray.df%>%filter(Drug_type=="PD1"|Drug_type=="PD1-2"|Drug_type=="PD1-3"), aes(x=Drug_type, y=dist, fill=BE2))+ 
  geom_boxplot(outlier.shape=NA)+theme_classic() + 
  theme(legend.direction = "horizontal",legend.position=c(0.7,0.2),axis.text.x = element_text(angle = 15)) +
  labs(title="Gene | Beta diversity(bray)", x="", y="distance")+ 
  stat_compare_means(label="p.format")

```


# pcoa - bray
```{r}
#PCoA

pcoa_bray <- pcoa(gene.bray.dist) 
pcoa_data <- data.frame(pcoa_bray$vectors[,1:2])
colnames(pcoa_data) <- c("PC1", "PC2")
eig <- pcoa_bray$value[,1]
pc1 <- eig[1]/sum(eig)*100
pc2 <- eig[2]/sum(eig)*100
pc1 <- paste0("PC1(",round(pc1,2),"%)")
pc2 <- paste0("PC2(",round(pc2,2),"%)")

### merge data frame
rownames(phe) <- phe$Fecal.sample.name
pcoa_data<-merge(pcoa_data, phe, by = "row.names")

ggplot(pcoa_data,aes(x=PC1,y=PC2,color=Native.place)) + geom_point() + stat_ellipse(aes(color=Native.place)) + xlab(pc1)+ylab(pc2) 

ggplot(pcoa_data,aes(x=PC1,y=PC2,color=Drug_type)) + geom_point() + stat_ellipse(aes(color=Drug_type)) + xlab(pc1)+ylab(pc2) 
ggplot(pcoa_data,aes(x=PC1,y=PC2,color=Treatment_type)) + geom_point() + stat_ellipse(aes(color=Treatment_type)) + xlab(pc1)+ylab(pc2) 
ggplot(pcoa_data,aes(x=PC1,y=PC2,color=Group)) + geom_point() + stat_ellipse(aes(color=Group)) + xlab(pc1)+ylab(pc2) 


ggplot(pcoa_data,aes(x=PC1,y=PC2,color=BE2)) + geom_point() + facet_wrap(~Drug_type,ncol=4) +
  coord_fixed() + theme(legend.position = "top") + stat_ellipse(aes(color=BE2)) +
  xlab(pc1)+ylab(pc2) 

ggplot(pcoa_data,aes(x=PC1,y=PC2,color=BE2)) + geom_point() + facet_wrap(~Group,ncol=2) +
  coord_fixed() + theme(legend.position = "top") + stat_ellipse(aes(color=BE2)) +
  xlab(pc1)+ylab(pc2) 

ggplot(pcoa_data,aes(x=PC1,y=PC2,color=BE2)) + geom_point() + facet_wrap(~Treatment_type,ncol=2) +
  coord_fixed() + theme(legend.position = "top") + stat_ellipse(aes(color=BE2)) +
  xlab(pc1)+ylab(pc2)

```




# phylum 
```{r}
phy.bray.dist <- read.table("../../Result/01.Profile/phylum_beta.matrix.xls")
phy.prf <- read.table("../../Result/01.Profile/phylum.rela.abun.xls")
phy.euclidean.dist <- as.matrix(vegdist(t(phy.prf),"euclidean",binary=TRUE))#euclidean距离,即欧式距离
```


```{r}
# bray curitis

g10.phy.bray.df <- reshapeDist(phy.bray.dist,phe,"Fecal.sample.name","Drug_type","BE2")
colnames(g10.phy.bray.df)[1:2] <- c("Drug_type","BE2")

g5.phy.bray.df <- reshapeDist(phy.bray.dist,phe,"Fecal.sample.name","Group","BE2")
colnames(g5.phy.bray.df)[1:2] <- c("Group","BE2")

g3.phy.bray.df <- reshapeDist(phy.bray.dist,phe,"Fecal.sample.name","Treatment_type","BE2")
colnames(g3.phy.bray.df)[1:2] <- c("Treatment_type","BE2")


```



```{r}
ggplot(g5.phy.bray.df, aes(x=Group, y=dist, fill = Group))+ 
  geom_boxplot()+theme_classic() + 
  theme() +
  labs(title="phylum | Beta diversity(bray)", x="", y="distance")+ 
  stat_compare_means(comparisons=compare_g5,label = "p.signif",method = "wilcox.test",size=3)+
  #stat_compare_means(label="p.format")+
ggplot(g5.phy.bray.df, aes(x=Group, y=dist, fill=BE2))+ 
  geom_boxplot(outlier.shape=NA)+theme_classic() + 
  theme(legend.direction = "horizontal",legend.position=c(0.7,0.2)) +
  labs(title="phylum | Beta diversity(bray)", x="", y="distance")+ 
  stat_compare_means(label="p.format")

```


```{r}
ggplot(g10.phy.bray.df, aes(x=Drug_type, y=dist, fill=BE2))+ 
  geom_boxplot(outlier.shape=NA)+theme_classic() + 
  theme(legend.direction = "horizontal",legend.position=c(0.7,0.2),axis.text.x = element_text(angle = 15)) +
  labs(title="Beta diversity(bray)", x="", y="distance")+ 
  stat_compare_means(label="p.format")+
  #+ geom_text(aes(label=dist, y=0), position=position_dodge(0.9), vjust=0) 
ggplot(g10.phy.bray.df, aes(x=Drug_type, y=dist, fill=Drug_type))+ 
  geom_boxplot(outlier.shape=NA)+theme_classic() + 
  theme(axis.text.x = element_text(angle = 15)) +
  labs(title="phylum | Beta diversity(bray)", x="", y="distance")+ 
  stat_compare_means(comparisons=compare_g10,label = "p.format",method = "wilcox.test",size=3)
  #stat_compare_means(label="p.format")


ggplot(g3.phy.bray.df, aes(x=Treatment_type, y=dist,fill=Treatment_type))+ 
  geom_boxplot(outlier.shape=NA)+theme_classic() + 
  theme() +
  labs(title="phylum | Beta diversity(bray)", x="", y="distance")+ 
  stat_compare_means(comparisons=compare_g3,label = "p.format",method = "wilcox.test",size=3)
  #stat_compare_means(label="p.format")+
ggplot(g3.phy.bray.df, aes(x=Treatment_type, y=dist, fill=BE2))+ 
  geom_boxplot(outlier.shape=NA)+theme_classic() + 
  theme(legend.direction = "horizontal",legend.position=c(0.7,0.2)) +
  labs(title="Beta diversity(bray)", x="", y="distance")+ 
  stat_compare_means(label="p.format")


```


# pcoa - bray
```{r}
#PCoA
pcoa_bray <- pcoa(genus.bray.dist) 
pcoa_data <- data.frame(pcoa_bray$vectors[,1:2])
colnames(pcoa_data) <- c("PC1", "PC2")
eig <- pcoa_bray$value[,1]
pc1 <- eig[1]/sum(eig)*100
pc2 <- eig[2]/sum(eig)*100
pc1 <- paste0("PC1(",round(pc1,2),"%)")
pc2 <- paste0("PC2(",round(pc2,2),"%)")

### merge data frame
rownames(phe) <- phe$Fecal.sample.name
pcoa_data<-merge(pcoa_data, phe, by = "row.names")

ggplot(pcoa_data,aes(x=PC1,y=PC2,color=Drug_type)) + geom_point() + stat_ellipse(aes(color=Drug_type)) + xlab(pc1)+ylab(pc2) 
ggplot(pcoa_data,aes(x=PC1,y=PC2,color=Treatment_type)) + geom_point() + stat_ellipse(aes(color=Treatment_type)) + xlab(pc1)+ylab(pc2) 
ggplot(pcoa_data,aes(x=PC1,y=PC2,color=Group)) + geom_point() + stat_ellipse(aes(color=Group)) + xlab(pc1)+ylab(pc2) 


ggplot(pcoa_data,aes(x=PC1,y=PC2,color=BE2)) + geom_point() + facet_wrap(~Drug_type,ncol=4) +
  coord_fixed() + theme(legend.position = "top") + stat_ellipse(aes(color=BE2)) +
  xlab(pc1)+ylab(pc2) 

ggplot(pcoa_data,aes(x=PC1,y=PC2,color=BE2)) + geom_point() + facet_wrap(~Group,ncol=2) +
  coord_fixed() + theme(legend.position = "top") + stat_ellipse(aes(color=BE2)) +
  xlab(pc1)+ylab(pc2) 

ggplot(pcoa_data,aes(x=PC1,y=PC2,color=BE2)) + geom_point() + facet_wrap(~Treatment_type,ncol=2) +
  coord_fixed() + theme(legend.position = "top") + stat_ellipse(aes(color=BE2)) +
  xlab(pc1)+ylab(pc2)

```